# Generated by Django 6.1 on 2026-08-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=100, unique=True)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('product_category', models.CharField(blank=True, max_length=255)),
                ('product_sub_category', models.CharField(blank=True, max_length=255)),
                ('collection_name', models.CharField(blank=True, max_length=255)),
                ('color_collection', models.CharField(blank=True, max_length=255)),
                ('product_color', models.CharField(blank=True, max_length=255)),
                ('product_name', models.CharField(max_length=500)),
                ('product_description', models.TextField(blank=True)),
                ('bullets', models.TextField(blank=True)),
                ('materials', models.TextField(blank=True)),
                ('product_dimensions', models.CharField(blank=True, max_length=500)),
                ('assembly_required', models.CharField(blank=True, max_length=100)),
                ('is_set', models.CharField(blank=True, max_length=100)),
                ('stackable', models.CharField(blank=True, max_length=100)),
                ('country_of_origin', models.CharField(blank=True, max_length=255)),
                ('item_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('map_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image_1', models.URLField(blank=True, max_length=1000)),
                ('image_2', models.URLField(blank=True, max_length=1000)),
                ('image_3', models.URLField(blank=True, max_length=1000)),
                ('image_4', models.URLField(blank=True, max_length=1000)),
                ('image_5', models.URLField(blank=True, max_length=1000)),
                ('product_url', models.URLField(blank=True, max_length=1000)),
                ('predicted_category', models.CharField(blank=True, max_length=500)),
                ('predicted_attributes', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('alternative_categories', models.JSONField(blank=True, default=list)),
                ('classification_status', models.CharField(default='pending', max_length=50)),
                ('manual_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
