# Generated by Django 6.1 on 2026-08-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_package_dimensions_product_pallet_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='package_dimensions',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_dimensions',
            field=models.TextField(blank=True),
        ),
    ]
