# Generated by Django 6.1 on 2026-08-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_package_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_dimensions',
            field=models.TextField(blank=True),
        ),
    ]
